apiVersion: v1
kind: Secret
metadata:
  name: destcluster
  namespace: <namespace where Velero is installed>
type: Opaque
data:
  host: <base64 encoded host URL>
  serviceaccount: <base64 encoded service account token here>
